### ISSUE TITLE
New Jukebox cause CPU load once it's paused.

### ISSUE THREAD

**Issue by sprnza** [airsonic/airsonic#638]
Hi there!
I've enabled the java jukebox and face with this issue when I start playback nothing strange happens. But when I click the pause button the main airsonic process starts to load on of CPU's cores up to 100% and it never  let it go until I restart it.

**Comment by sprnza** [comment]
[Log file](http://paste.speran.info/?13ef7d981e938d28#iApnfFLAwTznq7/rxF771vA038S3pUfM1Mu7IdoC1bk=) with `java --DEBUG`

**Comment by sprnza** [comment]
Version | 10.1.0-RELEASE – November 4, 2017

**Comment by biconou** [comment]
@sprnza I'll have a look as soon as possible. For the moment I am a bit busy.

**Comment by sprnza** [comment]
10.1.1-RELEASE – December 16, 2017 The issue is still there

**Comment by biconou** [comment]
Ok, i'll work on it in a few days.

**Comment by biconou** [comment]
OK, I've fixed it. I will submit a PR soon.

**Comment by DrAndri** [comment]
Hi

I pulled the #683 fix but the problem persists for me 

When I pause playback in java jukebox the CPU load goes way up and stays there until you resume playback or reload the webapp

**Comment by DrAndri** [comment]
[Log file](https://pastebin.com/BCb2HNwz) with logging.level.root=DEBUG

**Comment by biconou** [comment]
@DrAndri The fix works for me. What tool do you use to inspect CPU load ? I use top under linux.

**Comment by DrAndri** [comment]
Just realised that I had the old AudioPlayer-0.2.3.jar as well in my lib folder. It works after I removed that jar
